config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  get "sign_up" => "user/registrations#new"
  get "sign_in" => "user/sessions#new"
  delete "sign_out" => "user/sessions#destroy"
  namespace :user do
    resources :registrations, only: [:create, :edit, :update]
    resources :sessions, only: :create
  end
  root :to => "top#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_authentic do |c|
    c.login_field = :email
    c.validates_uniqueness_of_email_field_options({ value: true })
    c.merge_validates_length_of_password_field_options({ minimum: 6 })
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  protected

    def current_user_session
      return @current_user_session if defined?(@current_user_session)

      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)

      @current_user = current_user_session && current_user_session.user
    end

    def require_login
      unless current_user
        redirect_to sign_in_path
        flash[:error] = "ログインしてください"
        false
      end
    end

    def logged_in?
      current_user_session != nil
    end

    def after_login_path
      '/'
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :require_login

  def index
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  before_action :require_login
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < User::BaseController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params.to_h)
    begin
      User.transaction do
        if @user.valid?
          @user.save!
          flash.now[:notice] = "登録完了"
          redirect_to after_login_path
        else
          flash.now[:error] = "登録エラー"
          render action: :new
        end
      end
    rescue => e
      p e.message
    end
  end

  def edit
    redirect_to root_path if current_user.id != params[:id].to_i # || current_user == current_user.admin?
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = '更新しました'
      redirect_to root_path
    else
      flash.now[:error] = '更新に失敗しました'
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :slack_uid, :password, :password_confirmation)
    end

    def edit_user_params
      params.require(:user).permit(:email, :slack_uid)
    end      
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < User::BaseController
  skip_before_action :require_login, only: [:new, :create]

  def new
    redirect_to root_path if logged_in?
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params.to_h)

    if @user_session.save
      flash[:notice] = "ログインしました。"
      redirect_to root_path
    else
      flash.now[:error] = "ログインに失敗しました。"
      render action: :new
    end
  end

  def destroy
    current_user_session.destroy
    flash.now[:notice] = "ログアウトしました。"
    redirect_to root_path
  end

  private

    def user_session_params
      params.require(:user_session).permit(:email, :password)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Users::BaseController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params.to_h)
    begin
      User.transaction do
        if @user.valid?
          @user.save!
          flash[:notice] = "登録完了"
          redirect_to after_login_path
        else
          flash[:error] = "登録エラー"
          render action: :new
        end
      end
    rescue => e
      p e.message
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :slack_uid, :password, :password_confirmation)
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Users::BaseController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params.to_h)

    if @user_session.save
      flash[:notice] = "ログインしました。"
      redirect_to after_login_path
    else
      render action: :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "ログアウトしました。"
    redirect_to root_url
  end

  private

    def user_session_params
      params.require(:user_session).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LabAdmin</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <%= render 'shared/header' %>
  <div>
    <div class="container">
      <div class="pure-g center">
        <div class="pure-u-1-1">
          <% flash.each do |type,msg| %>
          <div class="pure-alert pure-alert-<%= type %>">
            <%= msg %>
          </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/shared/_header.html.erb
<div class="home-menu pure-menu pure-menu-horizontal">
  <a href="<%= root_path %>" class="pure-menu-heading">Lab Admin</a>
  <ul class="pure-menu-list">
    <% if logged_in? %>
    <li class="pure-menu-item">
      <%= link_to "Sign Out", sign_out_path, method: "delete", class: "pure-menu-link" %>
    </li>
    <li class="pure-menu-item">
      <a href="<%= edit_user_registration_path(current_user) %>" class="pure-menu-link"><%= current_user.email %></a>
    </li>
    <% else %>
    <li class="pure-menu-item">
      <%= link_to "Sign In", sign_in_path, method: "get", class: "pure-menu-link" %>
    </li>
    <li class="pure-menu-item">
      <%= link_to "Sign Up", sign_up_path, method: "get", class: "pure-menu-link" %>
    </li>
    <% end %>
  </ul>
</div>

app/views/top/index.html.erb
<h1 style="text-align: center;">Lab Admin</h1>